version: "3.9"
services:
  db:
    image: postgres:13.1
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kedro_local
      POSTGRES_USER: kedro
      POSTGRES_PASSWORD: kedro123
    ports:
      - "5432:5432"
  kedro:
    build: .
    environment:
      DB_HOST: db
      DB_USER: kedro
      DB_PASSWORD: kedro123
    depends_on:
      - db
